Fix pykickstart check

diff --git a/build-livecd-root b/build-livecd-root
--- a/build-livecd-root
+++ b/build-livecd-root
@@ -21,7 +21,7 @@ if [ $(id -u) != 0 ]; then
 	exit 1
 fi
 
-which livemedia-creator pykickstart >/dev/null || ( echo "Command(s) missing, install required tools" && exit 2 )
+which livemedia-creator ksflatten >/dev/null || ( echo "Command(s) missing, install required tools" && exit 2 )
 
 srcdir=$(readlink -f $(dirname $0))
 destdir=${2:-$srcdir}
