Fixes #10299 - PXELess discovery with TUI interface

diff --git a/build-livecd b/build-livecd
--- a/build-livecd
+++ b/build-livecd
@@ -1,37 +1,19 @@
 #!/bin/bash
 
-[[ -z "$1" ]] && echo "Usage: $0 fdi-name.ks [RELEASE_NUMBER]" && exit 1
+[[ -z "$1" ]] && echo "Usage: $0 fdi-name.ks [RELEASE_NUMBER] [VERSION]" && exit 1
 
-VERSION=$(git describe --abbrev=0 --tags)
+which git date base64 ksflatten >/dev/null || ( echo "Command(s) missing, install required tools" && exit 2 )
+
 RELEASE=$(date +%Y%m%d).${2:-1}
+VERSION=${3:-$(git describe --abbrev=0 --tags)}
 KS_INSTALL=fdi-install.ks
 KS_TARGET=fdi-image.ks
-OVERLAY="
-  /etc/default/discovery
-  /etc/NetworkManager/dispatcher.d/15-get-zip-server
-  /etc/profile.d/discovery.sh
-  /etc/rc.d/rc.local
-  /etc/systemd/system/discovery-fetch-extensions.path
-  /etc/systemd/system/discovery-fetch-extensions.service
-  /etc/systemd/system/discovery-register.service
-  /etc/systemd/system/discovery-start-extensions.service
-  /etc/systemd/system/nm-prepare.service
-  /usr/bin/discovery-debug
-  /usr/bin/discovery-fetch-extensions
-  /usr/bin/discovery-register
-  /usr/bin/discovery-start-extensions
-  /usr/bin/find-largest-rpms
-  /usr/bin/find-missing-libs
-  /usr/bin/nm-prepare
-  /usr/lib64/ruby/vendor_ruby/discovery.rb
-  /usr/share/fdi/commonfunc.sh
-  /usr/share/fdi/facts/discovery-facts.rb
-  /usr/share/fdi/RELEASE
-  /usr/share/fdi/VERSION"
 
 # prepare version and release files
 echo "$VERSION" > root/usr/share/fdi/VERSION
 echo "$RELEASE" > root/usr/share/fdi/RELEASE
+
+OVERLAY=$(find root -type f | cut -c 5-)
 
 # generate install overlay
 echo "# <generated by build-livecd>" > $KS_INSTALL
@@ -39,24 +21,15 @@ for FILE in $OVERLAY; do
 cat >> $KS_INSTALL <<EOF
 %post
 mkdir -p \$(dirname $FILE)
-cat > $FILE <<'CODE'
-$(cat root$FILE)
+base64 -d - >$FILE <<'CODE'
+$(cat root$FILE | base64 -w79)
 CODE
 %end
 EOF
 done
 cat >> $KS_INSTALL <<KS
 %post
-chmod +x \
-  /etc/NetworkManager/dispatcher.d/15-get-zip-server \
-  /etc/rc.d/rc.local \
-  /usr/bin/discovery-debug \
-  /usr/bin/discovery-fetch-extensions \
-  /usr/bin/discovery-register \
-  /usr/bin/discovery-start-extensions \
-  /usr/bin/find-largest-rpms \
-  /usr/bin/find-missing-libs \
-  /usr/bin/nm-prepare
+chmod +x $(find root -type f -executable | cut -c 5- | xargs echo)
 %end
 KS
 echo "# </generated by build-livecd>" >> $KS_INSTALL
diff --git a/build-livecd-root b/build-livecd-root
--- a/build-livecd-root
+++ b/build-livecd-root
@@ -19,6 +19,8 @@ if [ $(id -u) != 0 ]; then
   exit 1
 fi
 
+which livecd-creator isohybrid livecd-iso-to-pxeboot >/dev/null || ( echo "Command(s) missing, install required tools" && exit 2 )
+
 trap cleanup EXIT
 
 resultdir=$PWD
@@ -26,20 +28,25 @@ srcdir=$(readlink -f $(dirname $0))
 tmpdir=$(mktemp -d /tmp/build-fdi-XXXXXX)
 
 cd $srcdir
-last_tag=$(git describe --abbrev=0 --tags)
+last_tag=${1:-$(git describe --abbrev=0 --tags)}
 last_sha=$(git log --pretty=format:'%h' -n 1)
 
 cd $tmpdir
 echo Working in directory $tmpdir
 
 echo "* Running livecd-creator"
-livecd-creator -v --cache /var/cache/build-fdi --config $srcdir/fdi-image.ks -f fdi -t /tmp
+livecd-creator -v --title="Discovery Image" --compression-type=xz --cache /var/cache/build-fdi --config $srcdir/fdi-image.ks -f fdi -t /tmp
 
 if [ $? -ne 0 ]; then
     KEEP_TMPDIR=yes
     echo "Error creating livecd"
     exit 1
 fi
+
+echo "* Filtering ISO with isohybrid"
+cp fdi.iso fdi-bootable.iso
+isohybrid --partok --uefi fdi-bootable.iso
+mv fdi-bootable.iso $srcdir/fdi-bootable-${last_tag#release-}.iso
 
 echo "* Converting to initrd"
 livecd-iso-to-pxeboot $tmpdir/fdi.iso
